### ISSUE TITLE
local.ERROR: NotFound 

### ISSUE THREAD

**Issue by HarmJan1990** [MockingMagician/coinbase-pro-sdk#31]
Hi,

I'm getting this error when using the package in a Laravel Job script, any ideas?

``` [2022-04-01 08:30:11] 

local.ERROR: NotFound {"exception":"[object] (MockingMagician\\CoinbaseProSdk\\Functional\\Error\\ApiError(code: 0): NotFound at /home/dca-x8rfh/website.com/vendor/mocking-magician/coinbase-pro-sdk/src/Functional/Request/Request.php:132)
[stacktrace]
#0 /home/dca-x8rfh/website.com/vendor/mocking-magician/coinbase-pro-sdk/src/Functional/Request/RequestWithErrorManagement.php(41): MockingMagician\\CoinbaseProSdk\\Functional\\Request\\Request->send()
#1 /home/dca-x8rfh/website.com/vendor/mocking-magician/coinbase-pro-sdk/src/Functional/Connectivity/Orders.php(127): MockingMagician\\CoinbaseProSdk\\Functional\\Request\\RequestWithErrorManagement->send()
#2 /home/dca-x8rfh/website.com/vendor/mocking-magician/coinbase-pro-sdk/src/Functional/Connectivity/Orders.php(135): MockingMagician\\CoinbaseProSdk\\Functional\\Connectivity\\Orders->getOrderByIdRaw()
#3 /home/dca-x8rfh/website.com/app/Jobs/RunStrategy.php(122): MockingMagician\\CoinbaseProSdk\\Functional\\Connectivity\\Orders->getOrderById()
#4 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\RunStrategy->handle()
#5 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#9 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#10 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#11 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#13 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
#14 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#15 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/Middleware/WithoutOverlapping.php(71): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Queue\\Middleware\\WithoutOverlapping->handle()
#17 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#19 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#20 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#21 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#22 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
#23 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob()
#24 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#25 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#26 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#28 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#29 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#30 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#31 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#32 /home/dca-x8rfh/website.com/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#33 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#34 /home/dca-x8rfh/website.com/vendor/symfony/console/Application.php(1005): Illuminate\\Console\\Command->run()
#35 /home/dca-x8rfh/website.com/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#36 /home/dca-x8rfh/website.com/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#37 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#38 /home/dca-x8rfh/website.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#39 /home/dca-x8rfh/website.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#40 {main}
"} ```

**Comment by MockingMagician** [comment]
Hi @HarmJan1990 

Can you provide at least the code that fail and the "error message", we've got only stack trace here.

**Comment by MockingMagician** [comment]
@HarmJan1990 

Without seeing your code, I think the first thing to look at is getOrderByIdRaw() which would not find the order in question. It seems to me that the "local.ERROR NOT FOUND" is being brought up by the coinbase server which is not finding the order in question.

Do you have a try catch block in place to handle this kind of case?

**Comment by HarmJan1990** [comment]
Hi, i edited the original post. Here is the script.

```
$coinbase = CoinbaseFacade::createDefaultCoinbaseApi(
                    'https://api.exchange.coinbase.com',
                    $api_key,
                    $api_secret,
                    $api_passphrase
                );

                $accounts = $coinbase->accounts()->list();

                foreach ($accounts as $account) {
                    if($account->getCurrency() == 'EUR') {
                        $checkBalance = $account->getAvailableFunds();
                    }
                }

                if(isset($checkBalance) && $checkBalance >= $strategy->amount) {
                    foreach($markets as $market) {
                        $amount_used = $market->percentage * $percentagepoint;
                        $marketOrder = CoinbaseFacade::createMarketOrderToPlace(
                            MarketOrderToPlace::SIDE_BUY,
                            $market->market,
                            null,
                            $amount_used
                        );

                        $placeOrder = $coinbase->orders()->placeOrder($marketOrder);

                        if(isset($placeOrder)) {
                            $marketOrder = $coinbase->orders()->getOrderById($placeOrder->getId());

                            $fills = $coinbase->fills()->listFills($placeOrder->getId());

                            $price = 0;
                            $pricecount = 0;

                            foreach($fills as $fill) {
                                $price += $fill->getPrice();
                                $pricecount++;
                            }

                            if($pricecount > 0) {
                                $price /= $pricecount;
                            }

                            Order::create([
                                'external_id' => $placeOrder->getId(),
                                'market' => $market->market,
                                'side' => $marketOrder->getSide(),
                                'amount' => $marketOrder->getFilledSize(),
                                'price' => $price,
                                'amount_used' => $amount_used,
                                'exchange_name' => $exchange->exchange_name,
                                'exchange_id' => $strategy->exchange_id,
                                'user_id' => $strategy->user_id,
                                'strategy_id' => $strategy->id,
                            ]);
                        }
                    }
                }
```

I'll try with a try catch block first. Thanks.

**Comment by MockingMagician** [comment]
Hi @HarmJan1990 

> $placeOrder = $coinbase->orders()->placeOrder($marketOrder);
>
>                         if(isset($placeOrder)) {
>                             $marketOrder = $coinbase->orders()->getOrderById($placeOrder->getId());

First, but not really related, I think it is kind of duplicate here between placing the order and get it back a second time form server.

Not releated again, but please, use early return in your code for better reading and understanding, refacto example. Also I'll point out on error in your code (at the end, see  Order::create) :

```php

<?php

use MockingMagician\CoinbaseProSdk\CoinbaseFacade;
use MockingMagician\CoinbaseProSdk\Contracts\Connectivity\OrdersInterface;
use MockingMagician\CoinbaseProSdk\Functional\Build\MarketOrderToPlace;

$coinbase = CoinbaseFacade::createDefaultCoinbaseApi(
    'https://api.exchange.coinbase.com',
    $api_key,
    $api_secret,
    $api_passphrase
);

/** replace this code by the two lines behind
foreach ($accounts as $account) {
    if($account->getCurrency() == 'EUR') {
        $checkBalance = $account->getAvailableFunds();
    }
}
*/
$eurAccount = $coinbase->accounts()->getAccount('EUR');
$balance = $eurAccount->getAvailableFunds();

/** first early return */
if($balance < $strategy->amount) {
    return; //stop program or run exception or what you want
}
// like an implicit 'else' here, continue we have enough in balance, and it is according to strategy

foreach($markets as $market) {
    $amount_used = $market->percentage * $percentagepoint;
    $marketOrder = CoinbaseFacade::createMarketOrderToPlace(
        MarketOrderToPlace::SIDE_BUY,
        $market->market,
        null,
        $amount_used
    );

    try {
        $placeOrder = $coinbase->orders()->placeOrder($marketOrder);
    } catch (\MockingMagician\CoinbaseProSdk\Functional\Error\ApiError $exception) {
        // here you should log why that failed
        $logger->error('placing order has failed', [
            'market' => $market->market,
            'amount_used' => $amount_used,
            //... etc ...
        ]);
        continue; // continue for next market, else "place order" is OK no need for another check,
    }

    // except maybe checking if still pending...
    while ($placeOrder->getStatus() === OrdersInterface::STATUS_PENDING) {
        // may be you can wait here, like a sleep
        usleep(250000);
        // the update $placeOrder
        try {
            $placeOrder = $coinbase->orders()->getOrderById($placeOrder->getId());
        } catch (\MockingMagician\CoinbaseProSdk\Functional\Error\ApiError $exception) {
            // here you should log why that failed
             $logger->error('fetching order with id ' . $placeOrder->getId() . ' has failed', [
                 'place_order' => $placeOrder->getId(),
                 // etc ...
             ]);
            continue 2; // continue for next market, else place order is OK no need for another check,
        }
    }

    $fills = $coinbase->fills()->listFills($placeOrder->getId());

    $price = 0;
    $pricecount = 0;

    foreach($fills as $fill) {
        $price += $fill->getPrice();
        $pricecount++;
    }

    if($pricecount > 0) {
        $price /= $pricecount;
    }

    Order::create([
        'external_id' => $placeOrder->getId(),
        'market' => $market->market, // Custom market of you ?
        'side' => $marketOrder->getSide(),
        'amount' => $placeOrder->getFilledSize(), // <= it was an error here
        'price' => $price,
        'amount_used' => $amount_used,
        'exchange_name' => $exchange->exchange_name,
        'exchange_id' => $strategy->exchange_id,
        'user_id' => $strategy->user_id,
        'strategy_id' => $strategy->id,
    ]);
}

```

**Comment by HarmJan1990** [comment]
Hi @MockingMagician,

I refactored most of my code but some the part where you use
``` $coinbase->accounts()->getAccount('EUR'); ```
Gives a BadRequest error.

Thank you for your help and for noticing the errors in my code.
Any ideas on how to track the price better?

**Comment by MockingMagician** [comment]
> I refactored most of my code but the part where you use
> `$coinbase->accounts()->getAccount('EUR');`
> Gives a BadRequest error.

Yeah, my bad, getAccount expect id like string, exemple 18ba201e-6241-4efb-9b89-ed2885954566, then you can get currency from account and chek if euro :) , you was using the good method to do it

> Any ideas on how to track the price better?

You should use getSize information from $fill, example :

```php
$price = 0;
$size = 0;

foreach($fills as $fill) {
    $price += $fill->getPrice() * $fill->getSize();
    $size += $fill->getSize();
}

$price /= $size;
```

**Comment by HarmJan1990** [comment]
Thank you for your help and your work on this!
